<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mYEnZx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mYEnZx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1mYEnZx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1mYEnZx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1mYEnZx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1mYEnZx',
    'container.build_id' => 'b017d2f7',
    'container.build_time' => 1614605807,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1mYEnZx');
